spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${MYSQL_HOST}:5432/${MYSQL_DATABASE}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:t34ChGr4N53cr3T}
    cors:
      front-end: ${CORS_FRONTEND}